import { ICategory, IProduct } from './helper';

export const categories: ICategory[] = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Gadgets and devices',
    image: 'https://fakeimg.pl/200x100?text=Electronics&font=noto',
  },
  {
    id: '2',
    name: 'Clothing',
    description: 'Fashionable outfits',
    image: 'https://fakeimg.pl/200x100?text=Clothing&font=noto',
  },
  {
    id: '3',
    name: 'Home',
    description: 'Furniture and decor',
    image: 'https://fakeimg.pl/200x100?text=Home&font=noto',
  },
  {
    id: '4',
    name: 'Books',
    description: 'Reading materials',
    image: 'https://fakeimg.pl/200x100?text=Books&font=noto',
  },
  {
    id: '5',
    name: 'Toys',
    description: 'For kids and fun',
    image: 'https://fakeimg.pl/200x100?text=Toys&font=noto',
  },
  {
    id: '6',
    name: 'Sports',
    description: 'Fitness and outdoor gear',
    image: 'https://fakeimg.pl/200x100?text=Sports&font=noto',
  },
  {
    id: '7',
    name: 'Beauty',
    description: 'Cosmetics and skincare',
    image: 'https://fakeimg.pl/200x100?text=Beauty&font=noto',
  },
  {
    id: '8',
    name: 'Automotive',
    description: 'Car accessories and tools',
    image: 'https://fakeimg.pl/200x100?text=Automotive&font=noto',
  },
  {
    id: '9',
    name: 'Health',
    description: 'Health products and supplements',
    image: 'https://fakeimg.pl/200x100?text=Health&font=noto',
  },
  {
    id: '10',
    name: 'Furniture',
    description: 'Indoor and outdoor furniture',
    image: 'https://fakeimg.pl/200x100?text=Furniture&font=noto',
  },
  {
    id: '11',
    name: 'Appliances',
    description: 'Kitchen and home appliances',
    image: 'https://fakeimg.pl/200x100?text=Appliances&font=noto',
  },
  {
    id: '12',
    name: 'Stationery',
    description: 'Office and school supplies',
    image: 'https://fakeimg.pl/200x100?text=Stationery&font=noto',
  },
  {
    id: '13',
    name: 'Food & Beverages',
    description: 'Gourmet food and drinks',
    image: 'https://fakeimg.pl/200x100?text=Food+%26+Beverages&font=noto',
  },
  {
    id: '14',
    name: 'Jewelry',
    description: 'Rings, necklaces, and accessories',
    image: 'https://fakeimg.pl/200x100?text=Jewelry&font=noto',
  },
  {
    id: '15',
    name: 'Gardening',
    description: 'Tools and plants for the garden',
    image: 'https://fakeimg.pl/200x100?text=Gardening&font=noto',
  },
  {
    id: '16',
    name: 'Music',
    description: 'Instruments and sound equipment',
    image: 'https://fakeimg.pl/200x100?text=Music&font=noto',
  },
  {
    id: '17',
    name: 'Shoes',
    description: 'Footwear for all occasions',
    image: 'https://fakeimg.pl/200x100?text=Shoes&font=noto',
  },
  {
    id: '18',
    name: 'Pet Supplies',
    description: 'Products for your pets',
    image: 'https://fakeimg.pl/200x100?text=Pet+Supplies&font=noto',
  },
  {
    id: '19',
    name: 'Office Equipment',
    description: 'For your workspace needs',
    image: 'https://fakeimg.pl/200x100?text=Office+Equipment&font=noto',
  },
  {
    id: '20',
    name: 'Travel',
    description: 'Luggage, accessories, and more',
    image: 'https://fakeimg.pl/200x100?text=Travel&font=noto',
  },
];
export const products: IProduct[] = [
  {
    id: '1',
    name: 'Smartphone X1000',
    description: 'Latest model',
    image: 'https://fakeimg.pl/1000x400?text=Smartphone+X1000&font=noto',
    price: 699,
    quantity: 5,
    categoryId: '1',
    discount: 10,
  },
  {
    id: '2',
    name: 'Laptop Pro 15"',
    description: 'High performance',
    image: 'https://fakeimg.pl/1000x400?text=Laptop+Pro+15&font=noto',
    price: 999,
    quantity: 3,
    categoryId: '1',
  },
  {
    id: '3',
    name: 'Noise-cancelling Headphones',
    description: 'Noise-cancelling technology',
    image: 'https://fakeimg.pl/1000x400?text=Headphones&font=noto',
    price: 199,
    quantity: 0,
    categoryId: '1',
    discount: 15,
  },
  {
    id: '4',
    name: 'Comfortable Cotton T-shirt',
    description: 'Soft and breathable fabric',
    image: 'https://fakeimg.pl/1000x400?text=T-shirt&font=noto',
    price: 29,
    quantity: 10,
    categoryId: '2',
  },
  {
    id: '5',
    name: 'Modern Design Sofa',
    description: 'Sleek, modern design',
    image: 'https://fakeimg.pl/1000x400?text=Sofa&font=noto',
    price: 599,
    quantity: 2,
    categoryId: '3',
    discount: 20,
  },
  {
    id: '6',
    name: 'Stylish Wristwatch',
    description: 'Elegant and timeless design',
    image: 'https://fakeimg.pl/1000x400?text=Watch&font=noto',
    price: 129,
    quantity: 0,
    categoryId: '7',
  },
  {
    id: '7',
    name: 'Electric Grill',
    description: 'High-power grilling for indoors',
    image: 'https://fakeimg.pl/1000x400?text=Electric+Grill&font=noto',
    price: 89,
    quantity: 4,
    categoryId: '6',
    discount: 5,
  },
  {
    id: '8',
    name: 'Bluetooth Speaker',
    description: 'Portable audio experience',
    image: 'https://fakeimg.pl/1000x400?text=Bluetooth+Speaker&font=noto',
    price: 59,
    quantity: 10,
    categoryId: '1',
  },
  {
    id: '9',
    name: '4K Ultra HD TV',
    description: 'Crisp visuals and rich sound',
    image: 'https://fakeimg.pl/1000x400?text=4K+TV&font=noto',
    price: 1299,
    quantity: 3,
    categoryId: '1',
  },
  {
    id: '10',
    name: 'Smartwatch Z',
    description: 'Fitness tracking and notifications',
    image: 'https://fakeimg.pl/1000x400?text=Smartwatch+Z&font=noto',
    price: 249,
    quantity: 8,
    categoryId: '7',
    discount: 25,
  },
  {
    id: '11',
    name: 'Leather Wallet',
    description: 'Premium leather wallet',
    image: 'https://fakeimg.pl/1000x400?text=Leather+Wallet&font=noto',
    price: 49,
    quantity: 20,
    categoryId: '2',
  },
  {
    id: '12',
    name: 'Gaming Mouse',
    description: 'Precision for gamers',
    image: 'https://fakeimg.pl/1000x400?text=Gaming+Mouse&font=noto',
    price: 49,
    quantity: 6,
    categoryId: '1',
    discount: 30,
  },
  {
    id: '13',
    name: 'Ergonomic Office Chair',
    description: 'Comfortable seating for work',
    image: 'https://fakeimg.pl/1000x400?text=Office+Chair&font=noto',
    price: 299,
    quantity: 7,
    categoryId: '19',
  },
  {
    id: '14',
    name: 'Portable Power Bank',
    description: 'Charge your devices on the go',
    image: 'https://fakeimg.pl/1000x400?text=Power+Bank&font=noto',
    price: 29,
    quantity: 15,
    categoryId: '1',
  },
  {
    id: '15',
    name: 'Action Camera',
    description: 'Capture high-speed moments',
    image: 'https://fakeimg.pl/1000x400?text=Action+Camera&font=noto',
    price: 149,
    quantity: 10,
    categoryId: '1',
    discount: 10,
  },
  {
    id: '16',
    name: 'Cordless Vacuum Cleaner',
    description: 'Powerful cleaning, cord-free',
    image: 'https://fakeimg.pl/1000x400?text=Vacuum+Cleaner&font=noto',
    price: 199,
    quantity: 12,
    categoryId: '3',
  },
  {
    id: '17',
    name: 'Wireless Earbuds',
    description: 'Crystal clear sound',
    image: 'https://fakeimg.pl/1000x400?text=Earbuds&font=noto',
    price: 79,
    quantity: 8,
    categoryId: '1',
  },
  {
    id: '18',
    name: 'Adjustable Bed Frame',
    description: 'Perfect for any position',
    image: 'https://fakeimg.pl/1000x400?text=Bed+Frame&font=noto',
    price: 499,
    quantity: 3,
    categoryId: '10',
    discount: 15,
  },
  {
    id: '19',
    name: 'Camping Tent',
    description: 'Stay dry and comfortable outdoors',
    image: 'https://fakeimg.pl/1000x400?text=Camping+Tent&font=noto',
    price: 79,
    quantity: 5,
    categoryId: '6',
  },
  {
    id: '20',
    name: 'Smart Thermostat',
    description: 'Smart control for your home',
    image: 'https://fakeimg.pl/1000x400?text=Smart+Thermostat&font=noto',
    price: 149,
    quantity: 10,
    categoryId: '3',
  },
  {
    id: '21',
    name: 'Outdoor Grill',
    description: 'Cook your meals outdoors',
    image: 'https://fakeimg.pl/1000x400?text=Outdoor+Grill&font=noto',
    price: 250,
    quantity: 7,
    categoryId: '6',
    discount: 5,
  },
  {
    id: '22',
    name: 'Kitchen Mixer',
    description: 'Perfect for baking and cooking',
    image: 'https://fakeimg.pl/1000x400?text=Kitchen+Mixer&font=noto',
    price: 129,
    quantity: 15,
    categoryId: '11',
  },
  {
    id: '23',
    name: 'Barbecue Set',
    description: 'All the tools you need for grilling',
    image: 'https://fakeimg.pl/1000x400?text=Barbecue+Set&font=noto',
    price: 69,
    quantity: 4,
    categoryId: '6',
  },
  {
    id: '24',
    name: 'Designer Handbag',
    description: 'Luxury and elegance',
    image: 'https://fakeimg.pl/1000x400?text=Handbag&font=noto',
    price: 399,
    quantity: 3,
    categoryId: '2',
    discount: 20,
  },
  {
    id: '25',
    name: 'Smart Home Camera',
    description: 'Monitor your home remotely',
    image: 'https://fakeimg.pl/1000x400?text=Home+Camera&font=noto',
    price: 159,
    quantity: 8,
    categoryId: '1',
    discount: 10,
  },
  {
    id: '26',
    name: 'Electric Toothbrush',
    description: 'Advanced brushing technology',
    image: 'https://fakeimg.pl/1000x400?text=Toothbrush&font=noto',
    price: 39,
    quantity: 10,
    categoryId: '3',
  },
  {
    id: '27',
    name: 'Portable Heater',
    description: 'Stay warm wherever you are',
    image: 'https://fakeimg.pl/1000x400?text=Heater&font=noto',
    price: 99,
    quantity: 5,
    categoryId: '3',
    discount: 10,
  },
  {
    id: '28',
    name: 'Sleep Mask & Pillow Set',
    description: 'For a good night’s sleep',
    image: 'https://fakeimg.pl/1000x400?text=Sleep+Set&font=noto',
    price: 19,
    quantity: 25,
    categoryId: '2',
  },
  {
    id: '29',
    name: 'Wine Glass Set',
    description: 'Elegant glassware for wine lovers',
    image: 'https://fakeimg.pl/1000x400?text=Wine+Glass+Set&font=noto',
    price: 45,
    quantity: 18,
    categoryId: '3',
  },
  {
    id: '30',
    name: 'Electric Bike',
    description: 'Eco-friendly and fast',
    image: 'https://fakeimg.pl/1000x400?text=Electric+Bike&font=noto',
    price: 799,
    quantity: 6,
    categoryId: '6',
    discount: 25,
  },
  {
    id: '31',
    name: 'Smart Light Bulbs',
    description: 'Control lighting with your phone',
    image: 'https://fakeimg.pl/1000x400?text=Smart+Light+Bulbs&font=noto',
    price: 39,
    quantity: 40,
    categoryId: '3',
  },
  {
    id: '32',
    name: 'Gaming Chair',
    description: 'Comfort for long gaming sessions',
    image: 'https://fakeimg.pl/1000x400?text=Gaming+Chair&font=noto',
    price: 169,
    quantity: 12,
    categoryId: '19',
    discount: 5,
  },
  {
    id: '33',
    name: 'Portable Blender',
    description: 'Blend smoothies on the go',
    image: 'https://fakeimg.pl/1000x400?text=Portable+Blender&font=noto',
    price: 59,
    quantity: 20,
    categoryId: '3',
  },
  {
    id: '34',
    name: 'Compact Refrigerator',
    description: 'Perfect for small spaces',
    image: 'https://fakeimg.pl/1000x400?text=Compact+Fridge&font=noto',
    price: 199,
    quantity: 10,
    categoryId: '3',
    discount: 10,
  },
  {
    id: '35',
    name: 'Tennis Racket',
    description: 'High performance',
    image: 'https://fakeimg.pl/1000x400?text=Tennis+Racket&font=noto',
    price: 79,
    quantity: 6,
    categoryId: '19',
  },
  {
    id: '36',
    name: 'Backpack Pro',
    description: 'Spacious and durable',
    image: 'https://fakeimg.pl/1000x400?text=Backpack+Pro&font=noto',
    price: 59,
    quantity: 18,
    categoryId: '2',
  },
  {
    id: '37',
    name: 'VR Headset',
    description: 'Immersive virtual reality',
    image: 'https://fakeimg.pl/1000x400?text=VR+Headset&font=noto',
    price: 299,
    quantity: 4,
    categoryId: '1',
  },
  {
    id: '38',
    name: 'Fitness Tracker',
    description: 'Track your steps, sleep, and more',
    image: 'https://fakeimg.pl/1000x400?text=Fitness+Tracker&font=noto',
    price: 99,
    quantity: 15,
    categoryId: '4',
    discount: 10,
  },
  {
    id: '39',
    name: 'Smart Refrigerator',
    description: 'Wi-Fi enabled with touch controls',
    image: 'https://fakeimg.pl/1000x400?text=Smart+Fridge&font=noto',
    price: 1599,
    quantity: 2,
    categoryId: '3',
  },
  {
    id: '40',
    name: 'Robot Vacuum',
    description: 'Cleans automatically',
    image: 'https://fakeimg.pl/1000x400?text=Robot+Vacuum&font=noto',
    price: 249,
    quantity: 5,
    categoryId: '3',
    discount: 15,
  },
  {
    id: '41',
    name: 'Electric Kettle',
    description: 'Fast boiling for your convenience',
    image: 'https://fakeimg.pl/1000x400?text=Electric+Kettle&font=noto',
    price: 29,
    quantity: 12,
    categoryId: '3',
  },
  {
    id: '42',
    name: 'Weighted Blanket',
    description: 'For better sleep and comfort',
    image: 'https://fakeimg.pl/1000x400?text=Weighted+Blanket&font=noto',
    price: 89,
    quantity: 8,
    categoryId: '2',
    discount: 5,
  },
  {
    id: '43',
    name: 'Sushi Maker Kit',
    description: 'Make sushi at home',
    image: 'https://fakeimg.pl/1000x400?text=Sushi+Maker+Kit&font=noto',
    price: 39,
    quantity: 10,
    categoryId: '11',
  },
  {
    id: '44',
    name: 'Hydration Tracker Bottle',
    description: 'Track your water intake',
    image: 'https://fakeimg.pl/1000x400?text=Tracker+Bottle&font=noto',
    price: 35,
    quantity: 20,
    categoryId: '7',
    discount: 10,
  },
  {
    id: '45',
    name: 'Electric Skateboard',
    description: 'Cruise in style and speed',
    image: 'https://fakeimg.pl/1000x400?text=Electric+Skateboard&font=noto',
    price: 499,
    quantity: 3,
    categoryId: '6',
    discount: 25,
  },
  {
    id: '46',
    name: 'Smart Lock',
    description: 'Keyless home entry',
    image: 'https://fakeimg.pl/1000x400?text=Smart+Lock&font=noto',
    price: 129,
    quantity: 5,
    categoryId: '3',
  },
  {
    id: '47',
    name: 'Smart Plug',
    description: 'Control your appliances remotely',
    image: 'https://fakeimg.pl/1000x400?text=Smart+Plug&font=noto',
    price: 19,
    quantity: 25,
    categoryId: '3',
    discount: 10,
  },
  {
    id: '48',
    name: 'Digital Camera',
    description: 'Capture beautiful moments',
    image: 'https://fakeimg.pl/1000x400?text=Digital+Camera&font=noto',
    price: 399,
    quantity: 8,
    categoryId: '1',
  },
  {
    id: '49',
    name: 'Ceramic Cookware Set',
    description: 'Non-stick and eco-friendly',
    image: 'https://fakeimg.pl/1000x400?text=Cookware+Set&font=noto',
    price: 149,
    quantity: 6,
    categoryId: '11',
    discount: 15,
  },
  {
    id: '50',
    name: 'Portable Air Conditioner',
    description: 'Cool off anywhere',
    image: 'https://fakeimg.pl/1000x400?text=Portable+AC&font=noto',
    price: 349,
    quantity: 5,
    categoryId: '3',
  },
];
